# secrets is used to store confidential information in kubernetes
# we keep URL in config map but credentials are stored in secrets

apiVersion: v1
kind: secrets
metadata:
  name: secrets-basic-auth
data:
  username: kuzyhs87erw87w87t # here data is given base64 encoded
  password: fhk47yfsi7dygfxi7
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
      - secretref:
          name: secrets-basic-auth # here we are giving all the secret information 
